name: Deploy multiple mdBooks to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build all books
        run: |
          mdbook build qr-book
          mdbook build qr-dev
          mdbook build qr-algorithms
          mdbook build qr-modelling

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          mv qr-book/book deploy/qr
          mv qr-dev/book deploy/qr-dev
          mv qr-algorithms/book deploy/qr-algorithms
          mv qr-modelling/book deploy/qr-modelling

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
